### ISSUE TITLE
Actions are lost if state stream isn't setup

### ISSUE THREAD

**Issue by C2H6O** [floschu/AndroidReactor#4]
If `reactor.action.accept(Action.InitialObjectUid(uid))` is called before reactor.state is accessed, the Action is lost.

Currently the workaround that I've implemented is to access `state` property in the init { } block of my Reactor, and then send an Action.
```
init {
    state
    reactor.action.accept(Action.InitialObjectUid(objectUid))
}
```

Which is non-ideal, because you have to remember to call state.

**Comment by C2H6O** [comment]
Expanding a bit, the ObjectUid isn't part of the state, but the state is derived from it. So when Action.InitialObjectUid(objectUid) is mutated, the Mutation contains the state.

**Comment by C2H6O** [comment]
Ah, nice solution. As far as I understand, this.createStream() is called only after ViewModelReactor is fully initialized (versus just calling createStream()).

**Comment by floschu** [comment]
In `0.0.4` the state observable in `ViewModelReactor` is lazy again, due to the fact that the transform methods can rely on injected dependencies in the implementing reactor. These are however not injected yet at the time of the subclass `ViewModelReactor` initialization.
